services:
  postgres:
    image: postgres:16
    container_name: timelog
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: timelog
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./create-table.sql:/docker-entrypoint-initdb.d/01.create-table.sql

volumes:
  pgdata:
